### PR TITLE
Migrate deprecated React.PropTypes and View.propTypes

### LINKED ISSUE #145: View.propTypes is deprecated
Using View.PropTypes is deprecated since 0.44.0. facebook/react-native@53905a5
This is a breaking change through, it will require the latest react-native@0.44.0 installed.

### PR DESCRIPTION
**Pull request by alphasp**
fix #145, backward compatible with older version

### CODE REVIEW

**Comment by peacechen** [comment]
Here's how I support older and current versions of RN with their differing View PropTypes:

```
let rnVersion = Number.parseFloat(require('react-native/package.json').version);
...

static propTypes = {
  style: rnVersion >= 0.44 ? ViewPropTypes.style : View.propTypes.style,
  ...
}
```

**Comment by abdurrahmanekr** [comment]
Is the issue still ongoing? Does this resolve the PR problem? if resolve, please merge.

**Comment by iRoachie** [comment]
@ptomasroos Is everything good here?

**Comment by iRoachie** [comment]
@alphasp You missed https://github.com/happypancake/react-native-tab-navigator/blob/master/StaticContainer.js#L9

**Comment by iRoachie** [comment]
@alphasp You missed https://github.com/happypancake/react-native-tab-navigator/blob/master/StaticContainer.js#L9

**Comment by mgenov** [comment]
Looks replicated with #156.  It would be nice if either of them is merged as this could fix integration with 16.x versions of react.

**Comment by ptomasroos** [comment]
Hey ! I will handle review it tomorrow since I've been off for vacation, sorry for delay.

**Comment by ptomasroos** [comment]
Thanks for this, didnt know about the backwards compatible way.

**Comment by iRoachie** [comment]
@ptomasroos As soon as you can merge this let me know. Currently, right now it's breaking react-native-elements. I'll switch to use master for the time being

**Comment by ptomasroos** [comment]
It's already merged @iroachie

**Comment by iRoachie** [comment]
Yea it's merged, but you didn't publish a new version to npm

**Comment by ptomasroos** [comment]
0.3.4 is now released @iRoachie

**Comment by iRoachie** [comment]
Thanks!

**Pull request merged**
