### PR TITLE
Feature/example

### PR DESCRIPTION
**Pull request by gengjiawen**
Add example, see issue https://github.com/expo/react-native-tab-navigator/issues/99.

### CODE REVIEW

**Comment by ptomasroos** [comment]
Thanks @gengjiawen will take a look on this next week.

**Comment by ptomasroos** [comment]
@gengjiawen would you care to upgrade this to 0.46 so we can merge it? Would be a great addition!

**Comment by gengjiawen** [comment]
Any thought on https://github.com/react-community/create-react-native-app ?

**Comment by ptomasroos** [comment]
Perfect! Will try it out during the day and merge ASAP! Great work @gengjiawen

**Pull request merged**
