### PR TITLE
Add support for translucent tab bar

### PR DESCRIPTION
**Pull request by ksokhan**
Thought this might be a useful addition.

### CODE REVIEW

**Comment by alfonsodev** [comment]
Love the idea, 
but it needs to be updated from master, it doesn't work because now TabBar.js uses [Animated.View in the render method](https://github.com/exponentjs/react-native-tab-navigator/blob/master/TabBar.js#L20)

**Comment by ksokhan** [comment]
Cool, @alfonsodev. Will update when I get some time.

**Comment by ide** [comment]
We don't want to add a dependency on react-native-blur -- instead we should make the view type injectable.

**Comment by ksokhan** [comment]
Yea. fair @ide. I do wish blur was just baked into react-native.

**Comment by ptomasroos** [comment]
Will close this as no update has been provided from @ksokhan

**Pull request closed without merging**
